apiVersion: v1
kind: Service
metadata:
  name: cassandradatacenter-webhook-service
  labels:
    name: cass-operator-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    name: cass-operator
