apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Release.Name }}-prometheus-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  replicas: 1
  baseImage: quay.io/prometheus/prometheus
  version: v2.21.0
  serviceAccountName: {{ .Release.Name }}-prometheus-k8ssandra
  securityContext:
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ template "k8ssandra-cluster.name" . }}
{{- if not (empty .Values.monitoring.prometheus.externalUrl) }}
  externalUrl: {{ .Values.monitoring.prometheus.externalUrl }}
{{- end }}
{{- if not (empty .Values.monitoring.prometheus.routePrefix) }}
  routePrefix: {{ .Values.monitoring.prometheus.routePrefix }}
{{- end}}
  ruleSelector: {}
  alerting:
    alertmanagers: []
