{{- if and .Values.cassandra.auth.superuser.username (not .Values.cassandra.auth.superuser.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cassandra.clusterName }}-superuser
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ .Values.cassandra.auth.superuser.username | b64enc | quote }}
  password: {{ include "k8ssandra-common.password" . }}
{{- end }}