{{- if .Values.repair.reaper.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reaper-secret-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.repair.reaper.jmx.username }}
  username: {{ .Values.repair.reaper.jmx.username | b64enc | quote }}
  {{- else }}
  username: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.repair.reaper.jmx.password }}
  password: {{ .Values.repair.reaper.jmx.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}