{{- $traefik := .Values.ingress.traefik -}}
{{- if $traefik.enabled }}
{{- $releaseName := .Release.Name -}}
{{- $datacenterName := (index .Values.cassandra.datacenters 0).name -}}

{{- if $traefik.repair.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $releaseName }}-k8ssandra-repair
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.repair.entrypoints }}
    - {{ . }}
  {{- end }}
  routes:
  - match: Host(`{{ $traefik.repair.host }}`)
    kind: Rule
    services:
    - name: {{ $releaseName }}-reaper-k8ssandra-reaper-service
      kind: Service
      port: 8080
{{- end }}
{{- if $traefik.cassandra.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $releaseName }}-k8ssandra-cassandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.cassandra.entrypoints }}
    - {{ . }}
  {{- end }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $releaseName }}-{{ $datacenterName }}-service
          port: 9042
{{- end }}
{{- if $traefik.stargate.enabled }}
---
{{- if and $traefik.stargate.cassandra.enabled $traefik.cassandra.enabled }}
  {{- fail "ingress.traefik.stargate.cassandra.enabled and ingress.traefik.cassandra.enabled cannot both be enabled." }}
{{- end }}
{{- $stargateHost := required $traefik.stargate.host }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: k8ssandra-stargate
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  rules:
    - host: {{ $stargateHost }}
      http:
        paths:
          - path: /v1/auth
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8081
{{- if $traefik.stargate.graphql.enabled }}
    - host: {{ $stargateHost }}
      http:
        paths:
          - path: /graphql-schema
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8080
          - path: /graphql/
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8080
  {{- if $traefik.stargate.graphql.playground.enabled }}
          - path: /playground
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8080
  {{- end }}
{{- end }}
{{- if $traefik.stargate.rest.enabled }}
    - host: {{ $stargateHost }}
      http:
        paths:
          - path: /v2/
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8082
{{- end }}
{{- if $traefik.stargate.cassandra.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $releaseName }}-{{ $datacenterName }}-stargate
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.stargate.cassandra.entrypoints }}
  - {{ . }}
  {{- end }}
  routes:
    - match: Host(`{{ $stargateHost }}`)
      services:
        - name: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
          kind: Service
          port: 9042
{{- end }}
{{- end }}
{{- end }}
