# -- Replaces the chart name which is used in the metadata.name of objects
# created by this chart.
nameOverride: ""

# -- Replaces the value used for metadata.name in objects created by this chart.
# The default value has the form releaseName-chartName.
fullnameOverride: ""

# -- Labels to be added to all deployed resources
commonLabels: {}

# -- Sets the number of reaper-operator pods.
replicaCount: 1

image:
  # -- Container repository where the reaper-operator resides
  repository: docker.io/k8ssandra/reaper-operator

  # -- Pull policy for the operator container
  pullPolicy: IfNotPresent
  # -- Tag of the reaper-operator image to pull from image.repository
  tag: 0d6525659e9d

# -- References to secrets to use when pulling images. ref:
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

serviceAccount:
  # -- Annotations for the reaper-operator service account.
  annotations: {}

# -- Annotations for the reaper-operator pod.
podAnnotations: {}

# -- PodSecurityContext for the reaper-operator pod.
podSecurityContext: {}

securityContext:
  # -- Mark root filesystem as read only
  readOnlyRootFilesystem: true

  # -- Run reaper-operator container as non-root user
  runAsNonRoot: true

  # -- Group for the user running the reaper-operator container / process
  runAsGroup: 65534

  # -- User for running the reaper-operator container / process
  runAsUser: 65534

# -- Resources requests and limits for the cass-operator pod. We usually
# recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments
# with little resources, such as Minikube. If you do want to specify resources,
# uncomment the following lines, adjust them as necessary, and remove the curly
# braces after 'resources:'. limits: cpu: 100m memory: 128Mi requests: cpu: 100m
# memory: 128Mi
resources: {}
