apiVersion: v2
appVersion: 0.1.0
dependencies:
- name: k8ssandra-common
  repository: file://../k8ssandra-common
  version: 0.28.4
description: 'Configures and installs the Reaper Operator for Apache Cassandra. This tool  manages an external repair process for Apache Cassandra clusters. '
home: https://k8ssandra.io/
maintainers:
- email: k8ssandra-developers@googlegroups.com
  name: K8ssandra Team
  url: https://github.com/k8ssandra
name: reaper-operator
sources:
- https://github.com/k8ssandra/reaper-operator
- https://github.com/k8ssandra/k8ssandra/tree/main/charts/reaper-operator
type: application
version: 0.32.3
