apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-reaper-operator-lead-election-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-reaper-operator-leader-election-k8ssandra
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-reaper-operator-k8ssandra
