{{- if .Values.backupRestore.medusa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: medusa-config
data:
  medusa.ini: |-
    [cassandra]
    # The start and stop commands are not applicable in k8s.
    stop_cmd = /etc/init.d/cassandra stop
    start_cmd = /etc/init.d/cassandra start
    cql_username = cassandra
    cql_password = cassandra
    check_running = nodetool version

    [storage]
{{- if eq .Values.backupRestore.medusa.storage "s3" }}
    storage_provider = s3
{{- else if eq .Values.backupRestore.medusa.storage "gcs" }}
    storage_provider = gcs
{{- end }}
    bucket_name = {{ .Values.backupRestore.medusa.bucketName }}
    # TODO The file name needs to be parameterized. In the current set up it comes from the secret.
    key_file = /etc/medusa-secrets/medusa_s3_credentials

    [grpc]
    enabled = 1
    cassandra_url = http://localhost:7373/jolokia/

    [logging]
    level = DEBUG
  {{- end }}