{{- $releaseName := .Release.Name -}}
{{- $clusterName := .Values.clusterName -}}
{{- $datacenterName := .Values.datacenterName -}}
{{- $traefik := .Values.ingress.traefik -}}

{{- if and $traefik.enabled $traefik.repair.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $releaseName }}-k8ssandra-repair-redirect
spec:
  redirectRegex:
    permanent: true
    regex: ^http://{{ $traefik.repair.host }}/$
    replacement: http://{{ $traefik.repair.host }}/webui
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $releaseName }}-k8ssandra-repair
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.repair.entrypoints }}
    - {{ . }}
  {{- end }}
  routes:
  - match: Host(`{{ $traefik.repair.host }}`)
    kind: Rule
    middlewares:
    - {{ $releaseName }}-k8ssandra-repair-redirect
    services:
    - name: {{ $releaseName }}-reaper-k8ssandra-reaper-service
      kind: Service
      port: 8080
{{- end }}
{{- if and $traefik.enabled $traefik.cassandra.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $releaseName }}-k8ssandra-cassandra
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.cassandra.entrypoints }}
    - {{ . }}
  {{- end }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $clusterName }}-{{ $datacenterName }}-service
          port: 9042
{{- end }}
{{- if and $traefik.enabled $traefik.monitoring.grafana.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $releaseName }}-k8ssandra-monitoring-grafana
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.monitoring.grafana.entrypoints }}
    - {{ . }}
  {{- end }}
  routes:
  - match: Host(`{{ $traefik.monitoring.grafana.host }}`)
    kind: Rule
    services:
    # The grafana service name is hard coded because it does not look like grafana-operator
    # allows you to override the name.
    - name: grafana-service
      kind: Service
      port: 3000
{{- end }}
{{- if and $traefik.enabled $traefik.monitoring.prometheus.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $releaseName }}-k8ssandra-monitoring-prometheus
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.monitoring.prometheus.entrypoints }}
    - {{ . }}
  {{- end }}
  routes:
  - match: Host(`{{ $traefik.monitoring.prometheus.host }}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-prometheus-k8ssandra
      kind: Service
      port: 9090
{{- end }}
