apiVersion: v2
name: k8ssandra-operator
description: |
  Kubernetes operator which handles the provisioning and management of K8ssandra clusters.
type: application
version: 0.37.3
appVersion: 1.1.0
dependencies:
  - name: k8ssandra-common
    version: 0.28.4
    repository: file://../k8ssandra-common
  - name: cass-operator
    version: 0.35.3
    repository: file://../cass-operator
home: https://github.com/k8ssandra/k8ssandra-operator
sources:
  - https://github.com/k8ssandra/k8ssandra-operator
  - https://github.com/k8ssandra/k8ssandra/tree/main/charts/k8ssandra-operator
maintainers:
  - name: K8ssandra Team
    email: k8ssandra-developers@googlegroups.com
    url: https://github.com/k8ssandra
deprecated: false
