{{- if and .Values.k8ssandra.configuration.auth.enabled (not .Values.repair.reaper.cassandraUser.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.k8ssandra.clusterName }}-reaper
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ (default "reaper" .Values.repair.reaper.cassandraUser.username) | b64enc | quote }}
  password: {{ include "k8ssandra-common.password" . }}
{{- end }}
