{{- if .Values.reaper.enabled }}
apiVersion: reaper.cassandra-reaper.io/v1alpha1
kind: Reaper
metadata:
  name: {{ .Release.Name }}-reaper
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
spec:
  image: {{ .Values.reaper.image.repository }}:{{ .Values.reaper.image.tag }}
  serverConfig:
    autoScheduling:
      enabled: {{ .Values.reaper.autoschedule }}
      {{- if .Values.reaper.autoschedule }}
      {{- range $key, $value := .Values.reaper.autoschedule_properties }}
      {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
    storageType: cassandra
    jmxUserSecretName: {{ include "k8ssandra.reaperJmxUserSecretName" . }}
    cassandraBackend:
      {{- if .Values.cassandra.auth.enabled }}
      cassandraUserSecretName: {{ include "k8ssandra.reaperUserSecretName" . }}
      {{- end }}
      cassandraDatacenter:
        name: {{ include "k8ssandra.datacenterName" . }}
      replication:
        networkTopologyStrategy:
          {{ include "k8ssandra.datacenterName" . }}: {{ min (index .Values.cassandra.datacenters 0).size 3}}
  {{- if .Values.reaper.tolerations }}
  tolerations: {{ toYaml .Values.reaper.tolerations | nindent 4 }}
  {{- end }}
{{- end }}
