apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-prometheus-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-prometheus-k8ssandra
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-prometheus-k8ssandra
  namespace: {{ .Release.Namespace }}
