apiVersion: v2
name: k8ssandra-common
description: |
  Helper library containing functions used by many of the K8ssandra stack Helm charts.
type: library
version: 0.28.1
dependencies:
  - name: common
    version: 1.3.4
    repository: https://charts.bitnami.com/bitnami
home: https://k8ssandra.io/
sources:
  - https://github.com/k8ssandra/k8ssandra
  - https://github.com/k8ssandra/k8ssandra/tree/main/charts/k8ssandra-common
maintainers:
  - name: K8ssandra Team
    email: k8ssandra-developers@googlegroups.com
    url: https://github.com/k8ssandra
deprecated: false
