{{- if .Values.monitoring.grafana.provision_dashboards }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-k8ssandra-grafana-dashboards
  labels:
    grafana_dashboard: "true"
{{ include "k8ssandra.labels" . | indent 4 }}
data:
  cassandra-condensed.json: |
{{ .Files.Get "dashboards/cassandra-condensed.json" | indent 4 }}
  cassandra-overview.json: |
{{ .Files.Get "dashboards/overview.json" | indent 4 }}
  system-metrics.json: |
{{ .Files.Get "dashboards/system-metrics.json" | indent 4 }}
{{- if .Values.stargate.enabled }}
  stargate.json: |
{{ .Files.Get "dashboards/stargate.json" | indent 4 }}
{{- end }}
{{- end }}
