---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      {{- if not (empty .Values.monitoring.prometheus.routePrefix) }}
      url: http://{{ .Release.Name }}-prometheus-k8ssandra.{{ .Release.Namespace }}:9090/{{ .Values.monitoring.prometheus.routePrefix }}
      {{- else }}
      url: http://{{ .Release.Name }}-prometheus-k8ssandra.{{ .Release.Namespace }}:9090
      {{- end }}
      version: 1
  name: prometheus-datasources.yaml
