apiVersion: v2
name: cass-operator
description: |
  Kubernetes operator which handles the provisioning and management of Apache Cassandra clusters.
type: application
version: 0.29.3
appVersion: 1.7.1
dependencies:
  - name: k8ssandra-common
    version: 0.28.2
    repository: file://../k8ssandra-common
home: https://github.com/k8ssandra/cass-operator
sources:
  - https://github.com/k8ssandra/cass-operator
  - https://github.com/k8ssandra/k8ssandra/tree/main/charts/cass-operator
maintainers:
  - name: Cass Operator Team
    email: cass-operator@datastax.com
    url: https://github.com/k8ssandra/cass-operator
  - name: K8ssandra Team
    email: k8ssandra-developers@googlegroups.com
    url: https://github.com/k8ssandra
deprecated: false
