global:
  # -- Determines whether cass-operator only watch and manages
  # CassandraDatacenters in the same namespace in which the operator is deployed
  # or if watches and manages CassandraDatacenters across all namespaces.
  clusterScoped: false
  # -- List of namespaces to watch for CassandraDatacenter resources.
  # If empty, the operator will watch all namespaces in cluster-scope installation.
  # watchNamespaces: []
  # -- Annotations to be added to all deployed resources.
  commonAnnotations: {}
  # -- Labels to be added to all deployed resources.
  commonLabels: {}
  # -- Should we install cluster-scoped resources such as ClusterRole, ClusterRoleBinding
  clusterScopedResources: true
  # -- When set, this replaces the legacy imageConfig settings above. Set the default images used by
  # all the k8ssandra operators.
  imageConfig:
    images:
      system-logger:
        repository: "k8ssandra"
        name: "system-logger"
        tag: "v1.28.0"
      config-builder:
        repository: "datastax"
        name: "cass-config-builder"
        tag: "1.0-ubi"
      k8ssandra-client:
        repository: "k8ssandra"
        name: "k8ssandra-client"
        tag: "v0.8.5"
        # pullSecret: "k8ssandra-client-pull-secret" # Use of pullSecret removes the default pullSecrets for this image
        # pullPolicy: Always
    # -- defaults are used when other no override is present for the configured image or image type. All these values can be overridden under any image or image type.
    defaults:
      registry: "docker.io"
      pullPolicy: IfNotPresent
      # -- pullSecrets allow configuring the secret to use for pulling images from private registries.
      # pullSecrets:
      #   - my-secret-pull-registry
    # -- overrides will apply to all images discarding the settings in defaults or what individual images might have.
    # overrides:
    # -- registry to pull from
    # registry: "private-registry.local"
    # -- repository to use discarding all the other settings. If set to empty, repository part will be removed from the image path.
    # repository: "enterprise"
    # -- pullPolicy override the pullPolicy of images
    # pullPolicy: Never
    # -- pullSecrets removes all the other pullSecrets when used. Setting as empty array will remove pullSecrets from use.
    # pullSecrets:
    #   - "my-secret-pull-registry"
    # -- types are used as building blocks when serverVersion + serverType in the CassandraDatacenter is used
    types:
      cassandra:
        repository: "k8ssandra"
        name: "cass-management-api"
        suffix: "-ubi"
      dse:
        repository: "datastax"
        name: "dse-mgmtapi-6_8"
        suffix: "-ubi"
        # hcd:
        #   repository: "datastax"
        #   name: "hcd"
        #   suffix: "-ubi"
        #   pullSecret: "hcd-pull-secret" # Use of pullSecret removes the default pullSecrets for this image
        #   pullPolicy: IfNotPresent
# -- A name in place of the chart name which is used in the metadata.name of
# objects created by this chart.
nameOverride: ''
# -- A name in place of the value used for metadata.name in objects created by
# this chart. The default value has the form releaseName-chartName.
fullnameOverride: ''
# -- Labels to be added to all deployed resources.
commonLabels: {}
# -- Sets the number of cass-operator pods.
replicaCount: 1
# -- Configures admission webhooks deployed with cass-operator.
admissionWebhooks:
  # -- Turns the admission webhooks on or off. We recommend keeping them on.
  enabled: true
  # -- Use custom cert-manager certificate for injection instead of the self-signed as generated by cass-operator.
  # Use the form of namespace/certificate-name
  # customCertificate: casshook/joo
# Sets properties for the cass-operator container
image:
  # -- Container registry containing the repository where the image resides
  registry: docker.io
  # -- Docker repository for cass-operator
  repository: k8ssandra/cass-operator
  # -- Pull policy for the operator container
  pullPolicy: IfNotPresent
  # -- Tag of the cass-operator image to pull from image.repository
  tag: v1.28.0
  # -- Docker registry containing all cass-operator related images. Setting this
  # allows for usage of an internal registry without specifying serverImage,
  # configBuilderImage, and busyboxImage on all CassandraDatacenter objects.
  repositoryOverride:
  #   cassandra:
  #     "4.0.0": "k8ssandra/cassandra-ubi:latest"
  #   dse:
  #     "6.8.999": "datastax/dse-server-prototype:latest"
  # Overrides the global Image repository for Cassandra container
  registryOverride:
  # -- Overrides the namespace for all the images
  namespaceOverride:
# -- References to secrets to use when pulling images. See:
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# imagePullSecret: "{{ .Release.Name }}-registry"
# imagePullSecrets:
#   - name: "{{ .Release.Name }}-registry"
serviceAccount:
  # -- Annotations to add to the service account.
  annotations: {}
# -- Annotations for the cass-operator pod.
podAnnotations: {}
# -- PodSecurityContext for the cass-operator pod. See:
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext: {}
securityContext:
  # -- Run cass-operator container as non-root user
  runAsNonRoot: true
  # -- Group for the user running the cass-operator container / process
  runAsGroup: 65534
  # -- User for running the cass-operator container / process
  runAsUser: 65534
  # -- Run cass-operator container having read-only root file system permissions.
  readOnlyRootFilesystem: true
  # -- Do not allow privilege escalation for the cass-operator container.
  allowPrivilegeEscalation: false
# -- Resources requests and limits for the cass-operator pod. We usually
# recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments
# with little resources, such as Minikube. If you want to specify resources, add
# `requests` and `limits` for `cpu` and `memory` while removing the existing
# `{}`
resources: {}
# -- Node labels for operator pod assignment.
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
#
nodeSelector: {}
# -- Node tolerations for server scheduling to nodes with taints.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
#
tolerations: []
# -- Deprecated Use .global.imageConfig instead. Set the default images that cass-operator uses to deploy the Cassandra cluster. 
# systemLogger is our Vector image, configBuilder creates valid Cassandra configuration for
# 3.11/4.0 and DSE 6.8, while k8ssandraClient is used to build configs for 4.1 and newer
imageConfig:
  systemLogger: k8ssandra/system-logger:v1.28.0
  configBuilder: docker.io/datastax/cass-config-builder:1.0-ubi
  k8ssandraClient: docker.io/k8ssandra/k8ssandra-client:v0.8.5
  defaults:
    # Note, postfix is ignored if repository is not set
    cassandra:
      repository: "docker.io/k8ssandra/cass-management-api"
      suffix: "-ubi"
    dse:
      repository: "docker.io/datastax/dse-mgmtapi-6_8"
      suffix: "-ubi"
      # hcd:
      #   repository: "docker.io/datastax/hcd"
      #   suffix: "-ubi"
# -- metrics allows to change the configuration of how metrics are exposed. Default is
# to expose /metrics endpoint at port :8080. If you wish to make this available only on
# localhost (such as when using kube-rbac-proxy to secure access to them), set the value
# to 127.0.0.1:8080
metrics:
  address: ":8080"
  tls:
    # -- Enable TLS for metrics endpoint
    enabled: false
# -- Allows to disable the check for cert-manager. For helm template, use --api-versions=cert-manager.io/v1 instead
# disableCertManagerCheck: true
